### ISSUE TITLE
pywrapper issue

### ISSUE THREAD

**Issue by AABoyles** [openeventdata/stanford_pipeline#10]
Trying to use the pipeline, got this error:

    vagrant@vagrant-ubuntu-trusty-64:~/stanford_pipeline$ python process.py 
    INFO:stanford:Running.
    INFO:stanford:Returning 7612 total stories.
    INFO:stanford:Setting up CoreNLP.

    Setting up StanfordNLP. The program isn't dead. Promise.
    Exception AttributeError: "SockWrap instance has no attribute 'proc'" in <bound method SockWrap.__del__ of <stanford_corenlp_pywrapper.sockwrap.SockWrap instance at 0x7f1128cd17e8>> ignored
    Traceback (most recent call last):
      File "process.py", line 145, in <module>
        main()
      File "process.py", line 141, in main
        parser.stanford_parse(coll, stories, stanford_dir)
      File "/home/vagrant/stanford_pipeline/parser.py", line 33, in stanford_parse
        corenlp_libdir=stanford)
    TypeError: __init__() got an unexpected keyword argument 'corenlp_libdir'

Looks like there's a named argument that got removed in the coreNLP pywrapper. Or something like that. You guys know anything about this?

**Comment by johnb30** [comment]
I take it you're calling this from EL:DIABLO? Brendan updated his wrapper, so using my fork should be good https://github.com/johnb30/stanford_corenlp_pywrapper. I'll see about making changes in EL:DIABLO.

**Comment by johnb30** [comment]
#11 should fix this.
